### ISSUE TITLE
CLI HW - Stormy Ramsey

### ISSUE THREAD

**Issue by StormyRamsey** [ga-wdi-exercises/to_oz#204]
$ mkdir House
$ touch dorthy.txt toto.txt house.txt
$ mkdir Oz
$ touch GoodWitchofTheNorth.txt WickedWitchofTheEast.txt GoodWitchofTheSouth.txt WickedWithchofTheWest.txt
$ rm WickedWitchofTheEast.txt
$ mv ../dorthy.txt .

$ touch scarecrow.txt
$ touch tin man.txt
$ touch cowardly lion.txt 
$ mkdir Emerald City 
$ mv ./scarecrow.txt tin man.txt cowardly lion.txt Emerald City 

$ touch flying monkeys.txt
$ rm WickedWithchofTheWest.txt
$ echo "diploma" >> scarecrow.txt
$ echo "heart" >> tin man.txt 
$ echo "medal" >> cowardly lion.txt

**Comment by juancgarcia** [comment]
Very close. You created all the folders correctly, but since you never changed directories with `cd` some of the files weren't created in the right locations.

Before `$ touch dorthy.txt toto.txt` you should have done `cd House` so the files would be created "inside" of the `House` folder

Similarly you needed to `cd ../` next to get back to the base folder, and before creating the "Witches", `cd Oz` so that they will be created inside of "Oz"
