### ISSUE TITLE
Home Work

### ISSUE THREAD

**Issue by hewity** [ga-wdi-exercises/to_oz#50]
//**Create:**

mkdir House 
touch Dorothy.txt Toto.txt
mkdir Oz
cd Oz
touch Good\ Witch\ of\ the\ Norh.txt Wicked\ Witch\ of\ the\ East.txt Good\ Witch\ of\ the\ South.txt Wicked\ Witch\ of\ the\ West.txt
//**Delete:**
rm Wicked\ Witch\ of\ the\ East.txt

touch Scarecrow.txt Tin\ Man.txt Cowardly\ Lion.txt
mkdir  Emerald\ City.txt

/*At first didn't understand "the gang" because couldn't fined it on the list, Michel explained it to me what you mean. :) Move 'the gang' to "Emerald City" */

mv Scarecrow.txt Cowardly\ Lion.txt Tin\ Man.txt / ~wdi/excercise/Emerald\ City 
touch Flying\ Monkeys.txt
echo "a diploma" >> Scarecrow.txt
echo "a heart shaped watch" >> Tin\ Man.txt
echo "a medal" >> Cowardly\ Lion.txt

**Comment by adambray** [comment]
Good job overall! Few suggestions:
1. You correctly used backslashes to create spaces in filenames, but usually, I'd avoid using spaces in file names when possible. Instead, prefer underscores and lower-case, e.g. `wicked_witch_of_the_west`.
2. When moving the gang to emerald city, it's best to use a relative path
   Notice I can just use the directory name, because it's in the current directory that we're in.

```
mv Scarecrow.txt Cowardly\ Lion.txt Tin\ Man.txt Emerald_City 
```
1. Looks like you forgot to delete the Wicked Witch of the West in the last section.

Again though, good job!
