### ISSUE TITLE
Day 1 HW

### ISSUE THREAD

**Issue by habbywhyte** [ga-wdi-exercises/to_oz#57]
Completeness:4
Comfort:3.5

mkdir House
touch Dorothy Toto
mkdir Oz
touch Good Witch of the North, Wicked Witch of the East, Good Witch of the South, Wicked Witch of the West
rm Wicked Witch of the East
mv Dorothy Oz

touch Scarecrow, Tin Man, Cowardly Lion
mkdir Emerald City
mv the gang Emerald City

cd Oz
touch Flying Monkeys
rm Wicked Witch of the West

echo "a diploma" >> Oz/Scarecrow
echo  "a heart shaped watch" >> Oz/Tinman
echo "a medal" >> Oz/Lion

(Not too sure about echo...)

**Comment by adambray** [comment]
Hi Habby, you're off to a good start, but there are a couple of suggestions / corrections I'd like to note:
1. When you created the witches, you needed to `cd` into _Oz_ first. As you did it, they were created in the base folder, not in Oz.
2. Also related to the witches... you can't have spaces in file names (at least not without jumping  through hoops). Instead, use underscores to separate words in folder and file names. e.g. `wicked_witch_of_the_west`.  As it stands, your command created a bunch of files: one called "Good", another called "Witch", etc
3. Also related to that touch command, we _don't_ separate file names using commas on the command line. In your case, it was including the commas as part of the file names.

The correct version of that line would look something like:

```
$ touch good_witch_of_the_north good_witch_of_the_south good_witch_of_the_east good_witch_of_the_west
```

Regarding moving the gang to emerald city, the instructions were a bit ambiguous, but the intent was to move the scarecrow, tin man, etc to the emerald city. As you wrote this command, it gives an error because there are no files called 'the gang'.

Finally, re-peating your commands pasted here produces a lot of errors from the command line. 

My biggest suggestion is to do things _one step at a time_ and _verify the results._ For example, the issues in 1 and 2 probably would have been noticed had you run `ls` afterwards. Other commands gave me an error when I ran them, so when you were doing the HW, running them and verifying should have lead you to correct the error or ask for help.

I hope you understand that I'm being picky because the command line is important, and I want to make sure you're set up for success in the rest of the course! Happy to go over this 1:1 this week if you'd like.

Keep practicing and you'll be a CLI master in no time!  :+1:
